
  server:
    port: 9090

  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/company_catalogue_api_test
      username: root
      password: 29032005
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format-sql: true
          dialect: org.hibernate.dialect.MySQLDialect
        database: mysql

  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days


